DROP TRIGGER IF EXISTS `musical_player`.`Genre_AFTER_INSERT`;

DELIMITER $$
USE `musical_player`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musical_player`.`Genre_AFTER_INSERT` AFTER INSERT ON `Genre` FOR EACH ROW
BEGIN
	CALL updateGenresView();
END$$
DELIMITER ;
