DROP TRIGGER IF EXISTS `musical_player`.`Artist_BEFORE_INSERT`;

DELIMITER $$
USE `musical_player`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musical_player`.`Artist_BEFORE_INSERT` BEFORE INSERT ON `Artist` FOR EACH ROW
BEGIN
	IF EXISTS(SELECT * FROM Artist WHERE Artist.Name = NEW.Name) THEN 
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'Artist already exists';
    END IF;
END$$
DELIMITER ;
