DROP TRIGGER IF EXISTS `musical_player`.`Track_AFTER_UPDATE`;

DELIMITER $$
USE `musical_player`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musical_player`.`Track_AFTER_UPDATE` AFTER UPDATE ON `Track` FOR EACH ROW
BEGIN
	CALL updateTracksView();
END$$
DELIMITER ;
