DROP TRIGGER IF EXISTS `musical_player`.`Genre_AFTER_UPDATE`;

DELIMITER $$
USE `musical_player`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musical_player`.`Genre_AFTER_UPDATE` AFTER UPDATE ON `Genre` FOR EACH ROW
BEGIN
	CALL updateGenresView();
END$$
DELIMITER ;
