CREATE DEFINER=`root`@`localhost` PROCEDURE `addAlbum`(TITLE VARCHAR(45), IMAGE_URL VARCHAR(200), ARTIST_ID INT)
BEGIN
	INSERT INTO Album (Title, ImageUrl, Artist_idArtist) VALUES(TITLE, IMAGE_URL, ARTIST_ID);
END