CREATE DEFINER=`root`@`localhost` PROCEDURE `addPlaylist`(USER_ID INT, TITLE VARCHAR(45), IMAGE_URL VARCHAR(200))
BEGIN
	INSERT INTO Playlist (Title, ImageUrl, User_idUser) VALUES(TITLE, IMAGE_URL, USER_ID);
END