CREATE DEFINER=`root`@`localhost` PROCEDURE `registerUser`(LOGIN VARCHAR(45), PASSWORD_VALUE VARCHAR(45), PERMISSION_ID INT)
BEGIN
	INSERT INTO Users (Login, PasswordValue, permission) VALUES(LOGIN, PASSWORD_VALUE, PERMISSION_ID);
END