-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 14:15:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema musical_player
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `musical_player` ;

-- -----------------------------------------------------
-- Schema musical_player
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musical_player` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `musical_player` ;

-- -----------------------------------------------------
-- Table `Album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Album` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Album` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `ImageUrl` VARCHAR(200) NULL,
  `Artist_idArtist` INT NOT NULL,
  PRIMARY KEY (`idAlbum`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Album_has_Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Album_has_Genre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Album_has_Genre` (
  `Album_idAlbum` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  PRIMARY KEY (`Album_idAlbum`, `Genre_idGenre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artist` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Artist` (
  `idArtist` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `ImageUrl` VARCHAR(200) NULL,
  PRIMARY KEY (`idArtist`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Artist_has_Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artist_has_Genre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Artist_has_Genre` (
  `Artist_idArtist` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  PRIMARY KEY (`Artist_idArtist`, `Genre_idGenre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Genre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Permission` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Permission` (
  `idPermission` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `IsUser` INT(1) NOT NULL,
  `IsModer` INT(1) NOT NULL,
  `IsAdmin` INT(1) NOT NULL,
  PRIMARY KEY (`idPermission`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Playlist` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Playlist` (
  `idPlaylist` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `ImageUrl` VARCHAR(200) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPlaylist`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Playlist_has_Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Playlist_has_Genre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Playlist_has_Genre` (
  `Playlist_idPlaylist` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  PRIMARY KEY (`Playlist_idPlaylist`, `Genre_idGenre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Playlist_has_Track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Playlist_has_Track` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Playlist_has_Track` (
  `Playlist_idPlaylist` INT NOT NULL,
  `Track_idTrack` INT NOT NULL,
  PRIMARY KEY (`Playlist_idPlaylist`, `Track_idTrack`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Track` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Track` (
  `idTrack` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `AudioUrl` VARCHAR(200) NOT NULL,
  `Album_idAlbum` INT NOT NULL,
  PRIMARY KEY (`idTrack`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Track_has_Artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Track_has_Artist` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Track_has_Artist` (
  `Track_idTrack` INT NOT NULL,
  `Artist_idArtist` INT NOT NULL,
  PRIMARY KEY (`Track_idTrack`, `Artist_idArtist`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Track_has_Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Track_has_Genre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Track_has_Genre` (
  `Track_idTrack` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  PRIMARY KEY (`Track_idTrack`, `Genre_idGenre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Permission_idPermission` INT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
